server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;
    index index.php index.html;

    resolver 127.0.0.11 valid=10s ipv6=off;  # DNS interno do Docker

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        set $upstream php:9000;
        fastcgi_pass $upstream;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        fastcgi_connect_timeout 10s;
        fastcgi_send_timeout 60s;
        fastcgi_read_timeout 60s;
    }

    location ~ /\. {
        deny all;
    }
}